baseURL = "https://nathanmandell99.github.io/"
languageCode = 'en-us'
title = 'My New Hugo Site'
# theme = 'ananke'
[params]
name = "Nathan Mandell"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
